name: Hourly Feature Pipeline

on:
  schedule:
    - cron: '0 * * * *' # ev hour
  workflow_dispatch: # manual

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pandas numpy requests sqlalchemy psycopg2-binary python-dotenv google-generativeai

      - name: Run Feature Pipeline
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python feature_pipeline.py