name: Daily Model Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # ev day midnight
  workflow_dispatch: # manual

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pandas numpy xgboost scikit-learn joblib hopsworks sqlalchemy psycopg2-binary python-dotenv

      - name: Run Training Pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python train_pipeline.py