name: Daily Model Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # ev day midnight
  workflow_dispatch: # manual

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3.3 xgboost==2.0.3 scikit-learn==1.9.0 shap==0.44.1 "hopsworks[python]==5.0.4" sqlalchemy==2.0.41 python-dotenv==1.2.2 psycopg2-binary==2.9.12 "numpy<2.0.0" pyarrow==25.0.0
      - name: Run Training Pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python train_pipeline.py